"""initial schema

Revision ID: 4f848bbce7bf
Revises: 
Create Date: 2026-08-21 18:51:55.988406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f848bbce7bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_hash', sa.String(), nullable=False),
    sa.Column('source_text', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('translated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_hash')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lrclib_id', sa.Integer(), nullable=True),
    sa.Column('track_name', sa.String(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.Column('album_name', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('instrumental', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lrclib_id')
    )
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(), nullable=False),
    sa.Column('pos', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lemma', 'pos')
    )
    op.create_table('lyric_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['translation_id'], ['line_translations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('example_line_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['example_line_id'], ['lyric_lines.id'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=True),
    sa.Column('sense_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lyric_lines.id'], ),
    sa.ForeignKeyConstraint(['sense_id'], ['senses.id'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('senses')
    op.drop_table('lyric_lines')
    op.drop_table('vocabulary')
    op.drop_table('tracks')
    op.drop_table('line_translations')
    # ### end Alembic commands ###
