"""add youtube_video_id to tracks

Revision ID: ee24ce6fe730
Revises: 4f848bbce7bf
Create Date: 2026-09-25 16:17:42.879576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee24ce6fe730'
down_revision: Union[str, Sequence[str], None] = '4f848bbce7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('youtube_video_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'youtube_video_id')
    # ### end Alembic commands ###
